name: Build And Test

on:
  push:
    branches:
      - master
      - develop

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BUILD_CONFIGURATION: Release

jobs:
  baseline-tests:
    name: Baseline Test Suites
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore solution
        run: dotnet build Imposter.sln -c $BUILD_CONFIGURATION -p:IMPOSTER_LOG=true

      - name: Test Imposter.Abstractions.Tests
        run: dotnet test tests/Imposter.Abstractions.Tests/Imposter.Abstractions.Tests.csproj -c $BUILD_CONFIGURATION --no-build --list-tests

      - name: Test Imposter.CodeGenerator.Tests
        run: dotnet test tests/Imposter.CodeGenerator.Tests/Imposter.CodeGenerator.Tests.csproj -c $BUILD_CONFIGURATION --no-build --list-tests
         
  roslyn-matrix:
    timeout-minutes: 10
    name: Test for Roslyn ${{ matrix.roslynVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        roslynVersion:
          - '4.0'
          - '4.4'
          - '4.5'
          - '4.7'
          - '4.11'
          - '4.14'
          - '5.0.0-2.final'
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        if: matrix.roslynVersion != '5.0.0-2.final'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup .NET 10 SDK
        if: matrix.roslynVersion == '5.0.0-2.final'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build solution (Roslyn ${{ matrix.roslynVersion }})
        run: dotnet build Imposter.sln -c $BUILD_CONFIGURATION -p:ROSLYN_VERSION="${{ matrix.roslynVersion }}" -p:IMPOSTER_LOG=true

      - name: Run Imposter.Tests (Roslyn ${{ matrix.roslynVersion }})
        run: dotnet test tests/Imposter.Tests/Imposter.Tests.csproj -p:ROSLYN_VERSION="${{ matrix.roslynVersion }}" -c $BUILD_CONFIGURATION --no-build --list-tests

